"""
Simple WPS Office Style Verification Ribbon
Creates a professional blue ribbon with clickable verification details
"""
import fitz  # PyMuPDF
import json
from datetime import datetime
import os

class SimpleWPSRibbon:
    """Creates simple WPS Office style verification ribbons for PDFs"""
    
    def __init__(self):
        # WPS-style colors and dimensions
        self.ribbon_height = 35
        self.ribbon_color = (0.53, 0.81, 0.92)  # Sky blue #87CEEB
        self.text_color = (1, 1, 1)  # White text
        
    def add_wps_ribbon(self, pdf_path, output_path, cert_data):
        """Add WPS-style ribbon to PDF as visible overlay"""
        
        doc = fitz.open(pdf_path)
        
        # Add ribbon to first page only
        if len(doc) > 0:
            page = doc[0]
            page_rect = page.rect
            page_width = page_rect.width
            
            # Create ribbon area at the very top
            ribbon_rect = fitz.Rect(0, 0, page_width, self.ribbon_height)
            
            # Draw main ribbon background (sky blue)
            page.draw_rect(ribbon_rect, color=self.ribbon_color, fill=self.ribbon_color)
            
            # Add verification text
            main_text = "✓ CERTIFICATE VERIFIED - EduCerts"
            main_point = fitz.Point(15, 22)
            page.insert_text(main_text, main_text, fontsize=10, color=self.text_color)
            
            # Add click instruction
            click_text = "Click for verification details ›"
            click_point = fitz.Point(page_width - 200, 22)
            page.insert_text(click_point, click_text, fontsize=9, color=self.text_color)
            
            # Make ribbon clickable with real verification URL
            verify_url = f"https://educerts.verif.app/verify?id={cert_data.get('id', 'unknown')}"
            link_rect = fitz.Rect(0, 0, page_width, self.ribbon_height)
            link = {
                "kind": fitz.LINK_URI,
                "from": link_rect,
                "uri": verify_url
            }
            page.insert_link(link)
            
            print(f"✅ Added sky blue WPS ribbon with real verification link: {verify_url}")
        
        # Save with ribbon
        doc.save(output_path)
        doc.close()
        return output_path
    
    def _add_javascript(self, doc, cert_data):
        """Add JavaScript for verification dialog"""
        
        details = f"""
CERTIFICATE VERIFICATION STATUS

✅ STATUS: VERIFIED & AUTHENTIC
📋 Certificate ID: {cert_data.get('id', 'N/A')[:8]}...
👤 Student Name: {cert_data.get('student_name', 'N/A')}
📚 Course: {cert_data.get('course_name', 'N/A')}
📅 Issue Date: {cert_data.get('issued_at', 'N/A')}
🏢 Issuer: {cert_data.get('organization', 'EduCerts')}

🔒 SECURITY FEATURES:
• Digital Signature: Valid
• Content Integrity: Verified
• Registry Status: Confirmed

🌐 Verify online: https://educerts.io/verify?id={cert_data.get('id', '')}

Generated by EduCerts - Secure Digital Credentials
        """.strip()
        
        # Escape for JavaScript
        details = details.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')
        
        javascript_code = f"""
function showVerificationDetails() {{
    var verificationDetails = "{details}";
    
    try {{
        app.alert(verificationDetails, 3, 0, "Certificate Verification");
    }} catch(e) {{
        console.println("=== CERTIFICATE VERIFICATION ===");
        console.println(verificationDetails);
        console.println("==============================");
        app.alert("Verification details logged to console.");
    }}
}}
"""
        
        # Use the correct method for adding JavaScript
        try:
            doc.add_javascript("verification", javascript_code)
        except:
            # If add_javascript fails, just print a message
            print("Note: JavaScript could not be added, but ribbon is still visible")

def add_simple_wps_ribbon(pdf_path, output_path, cert_data):
    """Simple function to add WPS ribbon"""
    ribbon = SimpleWPSRibbon()
    return ribbon.add_wps_ribbon(pdf_path, output_path, cert_data)

# Test function
if __name__ == "__main__":
    print("🧪 Testing Simple WPS Ribbon")
    
    # Test with existing PDF
    input_pdf = "generated_certs/5e390ede-e06b-4e95-b3fd-0783472d47a9_signed.pdf"
    output_pdf = "generated_certs/simple_wps_test.pdf"
    
    test_data = {
        'id': '5e390ede-e06b-4e95-b3fd-0783472d47a9',
        'student_name': 'John Doe',
        'course_name': 'Computer Science Fundamentals',
        'issued_at': '2024-03-01',
        'organization': 'EduCerts University'
    }
    
    if os.path.exists(input_pdf):
        try:
            add_simple_wps_ribbon(input_pdf, output_pdf, test_data)
            print("✅ Simple WPS ribbon test completed!")
            print(f"📄 Open: {output_pdf}")
        except Exception as e:
            print(f"❌ Error: {e}")
    else:
        print(f"❌ Input PDF not found: {input_pdf}")
